name: Deploy dashboard to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4      # OK (dernière version)

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3   # ← nouvelle version
        with:
          path: .               # publie la racine du dépôt (index.html, .nojekyll, etc.)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v3           # ← nouvelle version
